//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchTags_SmartAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccFracc_Tags
    {
        public int IdTag { get; set; }
        public string RFID { get; set; }
        public string Indentity { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    }
}
