//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchTags_SmartAccess.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FraccEntitites : DbContext
    {
        public FraccEntitites(string connection = "name=FraccEntitites")
            : base(connection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccFracc_ErrorLogs> AccFracc_ErrorLogs { get; set; }
        public virtual DbSet<AccFracc_Tags> AccFracc_Tags { get; set; }
    }
}
